import type { Metadata } from "next";
import { Inter } from "next/font/google";
import style from "./section.module.css";
import { SectionProps } from "../../interface";
import DecoratorSVG from "./decoratorSVG";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Section({
  width,
  color,
  backgroundColor,
  id,
  children,
  dark
}: SectionProps) {
  return (
    <section
    id={id}
      className={style.section}
      style={{  width, color, backgroundColor }}
    >
      {children}
      <DecoratorSVG position="right" dark={dark} />
      <DecoratorSVG position="bottom" dark={dark} />
      <DecoratorSVG position="left" dark={dark} />
    </section>
  );
}